name: Test Pull Request
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint
      - name: Run Pylint
        run: pylint --rcfile=tests/pylintrc funkode/
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements_dev.txt
      - name: Run unit tests
        run: PYTHONPATH="$PYTHONPATH:funkode/" pytest --cov=funkode/ --cov-report=term-missing tests/
